#ifndef INCLUDE_CONSTANTS

#define SCREEN_WIDTH 800
#define SCREEN_HEIGHT 640
#define UNIT 32

// #define UNIT_WIDTH SCREEN_WIDTH / UNIT;
// #define UNIT_HEIGHT SCREEN_HEIGHT / UNIT;

#endif // !INCLUDE_CONSTANTS
